function jsquery(){var gb='',S=' top: -1000px;',pb='" for "gwt:onLoadErrorFn"',nb='" for "gwt:onPropertyErrorFn"',_='");',qb='#',Xb='.cache.js',sb='/',yb='//',Ob='0ECC00662E93A060D1A59E407CAC0132',Rb='26293BA44CAFFD7BCF5A577BA2EAB806',Sb='6138DC5B6310C68080B71D64EA3CEBF2',Tb='6FA4398B7D51EB940964CDD2D2520A46',Ub='9EC9911A655800ADA8AB462C2A49E611',Wb=':',Qb=':1',hb='::',T='<html><head><\/head><body><\/body><\/html>',kb='=',rb='?',mb='Bad handler "',Z='Chrome',Y='DOMContentLoaded',N='DUMMY',Vb='F35EB87901A6F9481A4C91CBEA19CC04',xb='base',vb='baseUrl',I='begin',O='body',H='bootstrap',ub='clear.cache.gif',jb='content',Ab='default',Zb='end',$='eval("',Pb='foo',Jb='gecko',Kb='gecko1_8',J='gwt.codesvr.jsquery=',K='gwt.codesvr=',ob='gwt:onLoadErrorFn',lb='gwt:onPropertyErrorFn',ib='gwt:property',cb='head',Ib='ie6',Hb='ie8',Gb='ie9',P='iframe',tb='img',V='javascript',Q='javascript:""',L='jsquery',Nb='jsquery.devmode.js',wb='jsquery.nocache.js',fb='jsquery::',Yb='loadExternalRefs',db='meta',bb='moduleRequested',ab='moduleStartup',Fb='msie',eb='name',zb='onload',Cb='opera',R='position:absolute; width:0; height:0; border:none; left: -1000px;',Eb='safari',U='script',Mb='selectingPermutation',M='startup',X='undefined',Lb='unknown',Bb='user.agent',W='var $wnd = window.parent;',Db='webkit';var p=window;var q=document;s(H,I);function r(){var a=p.location.search;return a.indexOf(J)!=-1||a.indexOf(K)!=-1}
function s(a,b){if(p.__gwtStatsEvent){p.__gwtStatsEvent({moduleName:L,sessionId:p.__gwtStatsSessionId,subSystem:M,evtGroup:a,millis:(new Date).getTime(),type:b})}}
jsquery.__sendStats=s;jsquery.__moduleName=L;jsquery.__errFn=null;jsquery.__moduleBase=N;jsquery.__softPermutationId=0;jsquery.__computePropValue=null;jsquery.__getPropMap=null;jsquery.__gwtInstallCode=function(){};jsquery.__gwtStartLoadingFragment=function(){return null};var t=function(){return false};var u=function(){return null};__propertyErrorFunction=null;var v=p.__gwt_activeModules=p.__gwt_activeModules||{};v[L]={moduleName:L};var w;function x(){z();return w}
function y(){z();return w.getElementsByTagName(O)[0]}
function z(){if(w){return}var a=q.createElement(P);a.src=Q;a.id=L;a.style.cssText=R+S;a.tabIndex=-1;q.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();w.write(T);w.close();var b=w.getElementsByTagName(O)[0];var c=w.createElement(U);c.language=V;var d=W;c.text=d;b.appendChild(c)}
function A(l){function m(a){function b(){if(typeof q.readyState==X){return typeof q.body!=X&&q.body!=null}return /loaded|complete/.test(q.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(q.removeEventListener){q.removeEventListener(Y,d,false)}if(e){clearInterval(e)}}}
if(q.addEventListener){q.addEventListener(Y,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function n(c){function d(a,b){a.removeChild(b)}
var e=y();var f=x();var g;if(navigator.userAgent.indexOf(Z)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode($));for(var j=0;j<c.length;j++){var k=window.JSON.stringify(c[j]);h.appendChild(f.createTextNode(k.substring(1,k.length-1)))}h.appendChild(f.createTextNode(_));g=f.createElement(U);g.language=V;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var j=0;j<c.length;j++){g=f.createElement(U);g.language=V;g.text=c[j];e.appendChild(g);d(e,g)}}}
jsquery.onScriptDownloaded=function(a){m(function(){n(a)})};s(ab,bb);var o=q.createElement(U);o.src=l;q.getElementsByTagName(cb)[0].appendChild(o)}
jsquery.__startLoadingFragment=function(a){return D(a)};jsquery.__installRunAsyncCode=function(a){var b=y();var c=x().createElement(U);c.language=V;c.text=a;b.appendChild(c);b.removeChild(c)};function B(){var c={};var d;var e;var f=q.getElementsByTagName(db);for(var g=0,h=f.length;g<h;++g){var j=f[g],k=j.getAttribute(eb),l;if(k){k=k.replace(fb,gb);if(k.indexOf(hb)>=0){continue}if(k==ib){l=j.getAttribute(jb);if(l){var m,n=l.indexOf(kb);if(n>=0){k=l.substring(0,n);m=l.substring(n+1)}else{k=l;m=gb}c[k]=m}}else if(k==lb){l=j.getAttribute(jb);if(l){try{d=eval(l)}catch(a){alert(mb+l+nb)}}}else if(k==ob){l=j.getAttribute(jb);if(l){try{e=eval(l)}catch(a){alert(mb+l+pb)}}}}}u=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;jsquery.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(qb);if(b==-1){b=a.length}var c=a.indexOf(rb);if(c==-1){c=a.length}var d=a.lastIndexOf(sb,Math.min(c,b));return d>=0?a.substring(0,d+1):gb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=q.createElement(tb);b.src=a+ub;a=e(b.src)}return a}
function g(){var a=u(vb);if(a!=null){return a}return gb}
function h(){var a=q.getElementsByTagName(U);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(wb)!=-1){return e(a[b].src)}}return gb}
function j(){var a=q.getElementsByTagName(xb);if(a.length>0){return a[a.length-1].href}return gb}
function k(){var a=q.location;return a.href==a.protocol+yb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==gb){l=h()}if(l==gb){l=j()}if(l==gb&&k()){l=e(q.location.href)}l=f(l);return l}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return jsquery.__moduleBase+a}
function E(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var j=[];var k=[];function l(a){var b=k[a](),c=j[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
k[zb]=function(){p.JsQuery={onLoadArray:[],onLoad:function(){for(i in p.JsQuery.onLoadArray)p.JsQuery.onLoadArray[i]()},ready:function(a){p.JsQuery.onLoadArray.push(a)}};p._$_=p.$;p.$=function(){return p.JsQuery};return Ab};j[zb]={'default':0,foo:1};k[Bb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Cb)!=-1}())return Cb;if(function(){return b.indexOf(Db)!=-1}())return Eb;if(function(){return b.indexOf(Fb)!=-1&&q.documentMode>=9}())return Gb;if(function(){return b.indexOf(Fb)!=-1&&q.documentMode>=8}())return Hb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Ib;if(function(){return b.indexOf(Jb)!=-1}())return Kb;return Lb};j[Bb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};t=function(a,b){return b in j[a]};jsquery.__getPropMap=function(){var a={};for(var b in j){a[b]=l(b)}return a};jsquery.__computePropValue=l;p.__gwt_activeModules[L].bindings=jsquery.__getPropMap;s(H,Mb);if(r()){return D(Nb)}var m;try{h([Ab,Eb],Ob);h([Pb,Eb],Ob);h([Ab,Eb],Ob+Qb);h([Pb,Eb],Ob+Qb);h([Ab,Cb],Rb);h([Pb,Cb],Rb);h([Ab,Cb],Rb+Qb);h([Pb,Cb],Rb+Qb);h([Ab,Ib],Sb);h([Pb,Ib],Sb);h([Ab,Ib],Sb+Qb);h([Pb,Ib],Sb+Qb);h([Ab,Kb],Tb);h([Pb,Kb],Tb);h([Ab,Kb],Tb+Qb);h([Pb,Kb],Tb+Qb);h([Ab,Hb],Ub);h([Pb,Hb],Ub);h([Ab,Hb],Ub+Qb);h([Pb,Hb],Ub+Qb);h([Ab,Gb],Vb);h([Pb,Gb],Vb);h([Ab,Gb],Vb+Qb);h([Pb,Gb],Vb+Qb);m=f[l(zb)][l(Bb)];var n=m.indexOf(Wb);if(n!=-1){g=parseInt(m.substring(n+1),10);m=m.substring(0,n)}}catch(a){}jsquery.__softPermutationId=g;return D(m+Xb)}
function F(){if(!p.__gwt_stylesLoaded){p.__gwt_stylesLoaded={}}s(Yb,I);s(Yb,Zb)}
B();jsquery.__moduleBase=C();v[L].moduleBase=jsquery.__moduleBase;var G=E();F();s(H,Zb);A(G);return true}
jsquery.succeeded=jsquery();