function jsquery(){var M='',jc='\n-',tb='" for "gwt:onLoadErrorFn"',rb='" for "gwt:onPropertyErrorFn"',Yb='"<script src=\\"',fb='"><\/script>',W='#',ic=');',ac='-\n',kc='-><\/scr',Zb='.cache.js\\"><\/scr" + "ipt>"',Y='/',Nb='43E29F8AA2C6449BA1DF2053920E3E79',Qb='512E0A8780750893B415564222E4B8F0',Rb='6457F2F6E0C8030EDB0E5B71D071F1B4',Vb=':',Pb=':1',lb='::',$b='<scr',eb='<script id="',ob='=',X='?',Ab='ActiveXObject',qb='Bad handler "',Bb='ChromeTab.ChromeFrame',Kb='Cross-site hosted mode not yet implemented. See issue ',Sb='D507B8259024E187570ECDA88C141B71',Wb='DOMContentLoaded',Tb='E0A5768D28A97571C901E1C1BC9C7138',Ub='E551E90BFDC70A03724AB64868960F69',gb='SCRIPT',db='__gwt_marker_jsquery',hb='base',_='baseUrl',Q='begin',P='bootstrap',zb='chromeframe',$='clear.cache.gif',nb='content',vb='default',hc='document.write(',V='end',dc='evtGroup: "loadExternalRefs", millis:(new Date()).getTime(),',fc='evtGroup: "moduleStartup", millis:(new Date()).getTime(),',Ob='foo',Hb='gecko',Ib='gecko1_8',R='gwt.codesvr=',S='gwt.hosted=',T='gwt.hybrid',sb='gwt:onLoadErrorFn',pb='gwt:onPropertyErrorFn',mb='gwt:property',Lb='http://code.google.com/p/google-web-toolkit/issues/detail?id=2079',Gb='ie6',Fb='ie8',Eb='ie9',Z='img',lc='ipt>',_b='ipt><!-',N='jsquery',bb='jsquery.nocache.js',kb='jsquery::',Xb='loadExternalRefs',ib='meta',cc='moduleName:"jsquery", sessionId:window.__gwtStatsSessionId, subSystem:"startup",',U='moduleStartup',Db='msie',jb='name',ub='onload',xb='opera',Cb='safari',ab='script',Mb='selectingPermutation',O='startup',ec='type: "end"});',gc='type: "moduleRequested"});',cb='undefined',Jb='unknown',wb='user.agent',yb='webkit',bc='window.__gwtStatsEvent && window.__gwtStatsEvent({';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s=M,t={},u=[],v=[],w=[],x=0,y,z;o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:Q});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=m.location.search;return (c.indexOf(R)!=-1||(c.indexOf(S)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(T)==-1}catch(a){}A=function(){return b};return b}
function B(){if(q&&r){q(y,N,s,x);o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:U,millis:(new Date).getTime(),type:V})}}
function C(){function e(a){var b=a.lastIndexOf(W);if(b==-1){b=a.length}var c=a.indexOf(X);if(c==-1){c=a.length}var d=a.lastIndexOf(Y,Math.min(c,b));return d>=0?a.substring(0,d+1):M}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(Z);b.src=a+$;a=e(b.src)}return a}
function g(){var a=E(_);if(a!=null){return a}return M}
function h(){var a=n.getElementsByTagName(ab);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(bb)!=-1){return e(a[b].src)}}return M}
function j(){var a;if(typeof isBodyLoaded==cb||!isBodyLoaded()){var b=db;var c;n.write(eb+b+fb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=gb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return M}
function k(){var a=n.getElementsByTagName(hb);if(a.length>0){return a[a.length-1].href}return M}
var l=g();if(l==M){l=h()}if(l==M){l=j()}if(l==M){l=k()}if(l==M){l=e(n.location.href)}l=f(l);s=l;return l}
function D(){var b=document.getElementsByTagName(ib);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(jb),g;if(f){f=f.replace(kb,M);if(f.indexOf(lb)>=0){continue}if(f==mb){g=e.getAttribute(nb);if(g){var h,j=g.indexOf(ob);if(j>=0){f=g.substring(0,j);h=g.substring(j+1)}else{f=g;h=M}t[f]=h}}else if(f==pb){g=e.getAttribute(nb);if(g){try{z=eval(g)}catch(a){alert(qb+g+rb)}}}else if(f==sb){g=e.getAttribute(nb);if(g){try{y=eval(g)}catch(a){alert(qb+g+tb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
v[ub]=function(){m.JsQuery={onLoadArray:[],onLoad:function(){for(i in m.JsQuery.onLoadArray)m.JsQuery.onLoadArray[i]()},ready:function(a){m.JsQuery.onLoadArray.push(a)}};m._$_=m.$;m.$=function(){return m.JsQuery};return vb};u[ub]={'default':0,foo:1};v[wb]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(xb)!=-1}())return xb;if(function(){return c.indexOf(yb)!=-1||function(){if(c.indexOf(zb)!=-1){return true}if(typeof window[Ab]!=cb){try{var b=new ActiveXObject(Bb);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Cb;if(function(){return c.indexOf(Db)!=-1&&n.documentMode>=9}())return Eb;if(function(){return c.indexOf(Db)!=-1&&n.documentMode>=8}())return Fb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Gb;if(function(){return c.indexOf(Hb)!=-1}())return Ib;return Jb};u[wb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};jsquery.onScriptLoad=function(a){jsquery.onScriptLoad=null;q=a;B()};if(A()){alert(Kb+Lb);return}D();C();o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:Mb});var H;try{F([vb,Gb],Nb);F([Ob,Gb],Nb);F([vb,Gb],Nb+Pb);F([Ob,Gb],Nb+Pb);F([vb,xb],Qb);F([Ob,xb],Qb);F([vb,xb],Qb+Pb);F([Ob,xb],Qb+Pb);F([vb,Eb],Rb);F([Ob,Eb],Rb);F([vb,Eb],Rb+Pb);F([Ob,Eb],Rb+Pb);F([vb,Ib],Sb);F([Ob,Ib],Sb);F([vb,Ib],Sb+Pb);F([Ob,Ib],Sb+Pb);F([vb,Fb],Tb);F([Ob,Fb],Tb);F([vb,Fb],Tb+Pb);F([Ob,Fb],Tb+Pb);F([vb,Cb],Ub);F([Ob,Cb],Ub);F([vb,Cb],Ub+Pb);F([Ob,Cb],Ub+Pb);H=w[G(ub)][G(wb)];var I=H.indexOf(Vb);if(I!=-1){x=Number(H.substring(I+1));H=H.substring(0,I)}}catch(a){return}var J;function K(){if(!r){r=true;B();if(n.removeEventListener){n.removeEventListener(Wb,K,false)}if(J){clearInterval(J)}}}
if(n.addEventListener){n.addEventListener(Wb,function(){K()},false)}var J=setInterval(function(){if(/loaded|complete/.test(n.readyState)){K()}},50);o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:V});o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:Xb,millis:(new Date).getTime(),type:Q});var L=Yb+s+H+Zb;n.write($b+_b+ac+bc+cc+dc+ec+bc+cc+fc+gc+hc+L+ic+jc+kc+lc)}
jsquery();