function jsquery(){var M='',gc='\n-',tb='" for "gwt:onLoadErrorFn"',rb='" for "gwt:onPropertyErrorFn"',Vb='"<script src=\\"',fb='"><\/script>',W='#',fc=');',Zb='-\n',hc='-><\/scr',Wb='.cache.js\\"><\/scr" + "ipt>"',Y='/',Kb='92FFD34E499B7C8B76D6F04055C2EEEE',Nb='94E7F3A13D9D8A74235AC4869F0D559D',Sb=':',Mb=':1',lb='::',Xb='<scr',eb='<script id="',ob='=',X='?',Ob='A363B4C40BAD6B1E460400DA365E207F',Pb='B2F070743862CF831BD704472E9DAAB0',qb='Bad handler "',Qb='CC0DDBD02E308093D90EA46B7B601366',Hb='Cross-site hosted mode not yet implemented. See issue ',Tb='DOMContentLoaded',Rb='E0D49C6B6488AEAA18BB31EE0650616E',gb='SCRIPT',db='__gwt_marker_jsquery',hb='base',_='baseUrl',Q='begin',P='bootstrap',$='clear.cache.gif',nb='content',vb='default',ec='document.write(',V='end',ac='evtGroup: "loadExternalRefs", millis:(new Date()).getTime(),',cc='evtGroup: "moduleStartup", millis:(new Date()).getTime(),',Lb='foo',Eb='gecko',Fb='gecko1_8',R='gwt.codesvr=',S='gwt.hosted=',T='gwt.hybrid',sb='gwt:onLoadErrorFn',pb='gwt:onPropertyErrorFn',mb='gwt:property',Ib='http://code.google.com/p/google-web-toolkit/issues/detail?id=2079',Db='ie6',Cb='ie8',Bb='ie9',Z='img',ic='ipt>',Yb='ipt><!-',N='jsquery',bb='jsquery.nocache.js',kb='jsquery::',Ub='loadExternalRefs',ib='meta',_b='moduleName:"jsquery", sessionId:window.__gwtStatsSessionId, subSystem:"startup",',U='moduleStartup',Ab='msie',jb='name',ub='onload',xb='opera',zb='safari',ab='script',Jb='selectingPermutation',O='startup',bc='type: "end"});',dc='type: "moduleRequested"});',cb='undefined',Gb='unknown',wb='user.agent',yb='webkit',$b='window.__gwtStatsEvent && window.__gwtStatsEvent({';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s=M,t={},u=[],v=[],w=[],x=0,y,z;o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:Q});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=m.location.search;return (c.indexOf(R)!=-1||(c.indexOf(S)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(T)==-1}catch(a){}A=function(){return b};return b}
function B(){if(q&&r){q(y,N,s,x);o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:U,millis:(new Date).getTime(),type:V})}}
function C(){function e(a){var b=a.lastIndexOf(W);if(b==-1){b=a.length}var c=a.indexOf(X);if(c==-1){c=a.length}var d=a.lastIndexOf(Y,Math.min(c,b));return d>=0?a.substring(0,d+1):M}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(Z);b.src=a+$;a=e(b.src)}return a}
function g(){var a=E(_);if(a!=null){return a}return M}
function h(){var a=n.getElementsByTagName(ab);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(bb)!=-1){return e(a[b].src)}}return M}
function j(){var a;if(typeof isBodyLoaded==cb||!isBodyLoaded()){var b=db;var c;n.write(eb+b+fb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=gb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return M}
function k(){var a=n.getElementsByTagName(hb);if(a.length>0){return a[a.length-1].href}return M}
var l=g();if(l==M){l=h()}if(l==M){l=j()}if(l==M){l=k()}if(l==M){l=e(n.location.href)}l=f(l);s=l;return l}
function D(){var b=document.getElementsByTagName(ib);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(jb),g;if(f){f=f.replace(kb,M);if(f.indexOf(lb)>=0){continue}if(f==mb){g=e.getAttribute(nb);if(g){var h,j=g.indexOf(ob);if(j>=0){f=g.substring(0,j);h=g.substring(j+1)}else{f=g;h=M}t[f]=h}}else if(f==pb){g=e.getAttribute(nb);if(g){try{z=eval(g)}catch(a){alert(qb+g+rb)}}}else if(f==sb){g=e.getAttribute(nb);if(g){try{y=eval(g)}catch(a){alert(qb+g+tb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
v[ub]=function(){m.JsQuery={onLoadArray:[],onLoad:function(){for(i in m.JsQuery.onLoadArray)m.JsQuery.onLoadArray[i]()},ready:function(a){m.JsQuery.onLoadArray.push(a)}};m.$=function(){return m.JsQuery};return vb};u[ub]={'default':0,foo:1};v[wb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(xb)!=-1}())return xb;if(function(){return b.indexOf(yb)!=-1}())return zb;if(function(){return b.indexOf(Ab)!=-1&&n.documentMode>=9}())return Bb;if(function(){return b.indexOf(Ab)!=-1&&n.documentMode>=8}())return Cb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Db;if(function(){return b.indexOf(Eb)!=-1}())return Fb;return Gb};u[wb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};jsquery.onScriptLoad=function(a){jsquery.onScriptLoad=null;q=a;B()};if(A()){alert(Hb+Ib);return}D();C();o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:Jb});var H;try{F([vb,zb],Kb);F([Lb,zb],Kb);F([vb,zb],Kb+Mb);F([Lb,zb],Kb+Mb);F([vb,Cb],Nb);F([Lb,Cb],Nb);F([vb,Cb],Nb+Mb);F([Lb,Cb],Nb+Mb);F([vb,Db],Ob);F([Lb,Db],Ob);F([vb,Db],Ob+Mb);F([Lb,Db],Ob+Mb);F([vb,xb],Pb);F([Lb,xb],Pb);F([vb,xb],Pb+Mb);F([Lb,xb],Pb+Mb);F([vb,Bb],Qb);F([Lb,Bb],Qb);F([vb,Bb],Qb+Mb);F([Lb,Bb],Qb+Mb);F([vb,Fb],Rb);F([Lb,Fb],Rb);F([vb,Fb],Rb+Mb);F([Lb,Fb],Rb+Mb);H=w[G(ub)][G(wb)];var I=H.indexOf(Sb);if(I!=-1){x=Number(H.substring(I+1));H=H.substring(0,I)}}catch(a){return}var J;function K(){if(!r){r=true;B();if(n.removeEventListener){n.removeEventListener(Tb,K,false)}if(J){clearInterval(J)}}}
if(n.addEventListener){n.addEventListener(Tb,function(){K()},false)}var J=setInterval(function(){if(/loaded|complete/.test(n.readyState)){K()}},50);o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:P,millis:(new Date).getTime(),type:V});o&&o({moduleName:N,sessionId:p,subSystem:O,evtGroup:Ub,millis:(new Date).getTime(),type:Q});var L=Vb+s+H+Wb;n.write(Xb+Yb+Zb+$b+_b+ac+bc+$b+_b+cc+dc+ec+L+fc+gc+hc+ic)}
jsquery();